global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'rust-bc-nodes'
    static_configs:
      - targets:
          - 'node1:8080'
          - 'node2:8080'
          - 'node3:8080'
          - 'orderer1:8080'
          - 'orderer2:8080'
          - 'orderer3:8080'
        labels:
          network: 'local-test'
    metrics_path: '/metrics'
