//! Internal PKI — node certificate provisioning.
//!
//! Provides a self-contained CA that issues short-lived TLS certificates for
//! P2P nodes, eliminating the dependency on an external CA.
//!
//! # Environment variables
//!
//! | Variable | Description |
//! |----------|-------------|
//! | `TLS_CA_CERT_PATH` | Path to the CA certificate PEM file (for distribution) |
//! | `TLS_CA_KEY_PATH`  | Path to the CA private key PEM file (for signing)      |
//!
//! # Design note
//!
//! When loading an existing CA from disk, this module reconstructs the rcgen
//! `Certificate` from the persisted key using a fixed Common Name
//! (`INTERNAL_CA_CN`). For the chain to validate, the CA cert on disk must have
//! been generated by `NodeCaConfig::generate` (which uses the same CN and key).
//!
//! # Example
//!
//! ```no_run
//! use rust_bc::pki::{NodeCaConfig, sign_node_cert};
//!
//! let ca = NodeCaConfig::from_env().unwrap();
//! let cert = sign_node_cert("node-1", &ca, 365).unwrap();
//! cert.save(
//!     std::path::Path::new("/etc/tls/node.crt"),
//!     std::path::Path::new("/etc/tls/node.key"),
//! ).unwrap();
//! ```

use rcgen::{BasicConstraints, CertificateParams, DnType, IsCa, KeyPair};
use rustls::pki_types::CertificateDer;
use std::path::Path;

/// Common Name used for all internally-generated CA certificates.
pub const INTERNAL_CA_CN: &str = "Rust-BC Internal CA";

/// CA certificate validity (10 years from a fixed epoch).
const CA_NOT_BEFORE: time::OffsetDateTime = time::macros::datetime!(2024-01-01 0:00 UTC);
const CA_NOT_AFTER: time::OffsetDateTime = time::macros::datetime!(2034-01-01 0:00 UTC);

// ── Errors ─────────────────────────────────────────────────────────────────

#[derive(Debug, thiserror::Error)]
pub enum PkiError {
    #[error("rcgen error: {0}")]
    Rcgen(#[from] rcgen::Error),
    #[error("io error: {0}")]
    Io(#[from] std::io::Error),
    #[error("TLS_CA_CERT_PATH must be set for PKI provisioning")]
    MissingCaCert,
    #[error("TLS_CA_KEY_PATH must be set for PKI provisioning")]
    MissingCaKey,
    #[error("cannot read file '{0}': {1}")]
    ReadFile(String, #[source] std::io::Error),
}

// ── IssuedNodeCert ─────────────────────────────────────────────────────────

/// A node certificate issued by the internal CA.
pub struct IssuedNodeCert {
    /// DER-encoded signed certificate (ready for use with rustls).
    pub cert_der: CertificateDer<'static>,
    /// PEM-encoded certificate (for writing to disk or embedding in configs).
    pub cert_pem: String,
    /// PEM-encoded private key.
    pub key_pem: String,
}

impl IssuedNodeCert {
    /// Write cert and key to the given paths as PEM files.
    pub fn save(&self, cert_path: &Path, key_path: &Path) -> Result<(), PkiError> {
        std::fs::write(cert_path, self.cert_pem.as_bytes())?;
        std::fs::write(key_path, self.key_pem.as_bytes())?;
        Ok(())
    }
}

// ── NodeCaConfig ───────────────────────────────────────────────────────────

/// An internal CA that can sign P2P node certificates.
pub struct NodeCaConfig {
    ca_cert: rcgen::Certificate,
    ca_key: KeyPair,
}

impl std::fmt::Debug for NodeCaConfig {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("NodeCaConfig")
            .field("ca_cn", &INTERNAL_CA_CN)
            .finish_non_exhaustive()
    }
}

impl NodeCaConfig {
    /// Load a CA from PEM key file, reconstructing the rcgen signing cert.
    ///
    /// The `cert_path` file is validated (must be readable) but its content is
    /// used only for distribution — the signing cert is rebuilt from the key
    /// using [`INTERNAL_CA_CN`], which must match how the CA was originally
    /// generated.
    pub fn from_pem_files(cert_path: &Path, key_path: &Path) -> Result<Self, PkiError> {
        // Validate both paths are readable.
        let _cert_pem = std::fs::read_to_string(cert_path)
            .map_err(|e| PkiError::ReadFile(cert_path.display().to_string(), e))?;
        let key_pem = std::fs::read_to_string(key_path)
            .map_err(|e| PkiError::ReadFile(key_path.display().to_string(), e))?;
        let ca_key = KeyPair::from_pem(&key_pem)?;
        let ca_cert = make_ca_cert_params()?.self_signed(&ca_key)?;
        Ok(Self { ca_cert, ca_key })
    }

    /// Load from `TLS_CA_CERT_PATH` + `TLS_CA_KEY_PATH` environment variables.
    pub fn from_env() -> Result<Self, PkiError> {
        let cert_path = std::env::var("TLS_CA_CERT_PATH").map_err(|_| PkiError::MissingCaCert)?;
        let key_path = std::env::var("TLS_CA_KEY_PATH").map_err(|_| PkiError::MissingCaKey)?;
        Self::from_pem_files(Path::new(&cert_path), Path::new(&key_path))
    }

    /// Generate a new self-signed CA in memory.
    ///
    /// Returns `(NodeCaConfig, cert_pem, key_pem)` so the caller can persist
    /// the cert and key to disk for future reloads and for distribution to
    /// peer nodes.
    pub fn generate() -> Result<(Self, String, String), PkiError> {
        let ca_key = KeyPair::generate()?;
        let ca_cert = make_ca_cert_params()?.self_signed(&ca_key)?;
        let cert_pem = ca_cert.pem();
        let key_pem = ca_key.serialize_pem();
        Ok((Self { ca_cert, ca_key }, cert_pem, key_pem))
    }
}

/// Build `CertificateParams` for the internal CA (fixed CN and validity).
fn make_ca_cert_params() -> Result<CertificateParams, PkiError> {
    let mut params = CertificateParams::new(vec![])?;
    params
        .distinguished_name
        .push(DnType::CommonName, INTERNAL_CA_CN);
    params.is_ca = IsCa::Ca(BasicConstraints::Unconstrained);
    params.not_before = CA_NOT_BEFORE;
    params.not_after = CA_NOT_AFTER;
    Ok(params)
}

// ── sign_node_cert ─────────────────────────────────────────────────────────

/// Generate a new ECDSA P-256 key pair and issue a TLS certificate for
/// `node_id`, signed by `ca`.
///
/// The certificate carries `node_id` as both the Common Name and a DNS SAN,
/// and is valid for `ttl_days` days from the current time.
pub fn sign_node_cert(
    node_id: &str,
    ca: &NodeCaConfig,
    ttl_days: u32,
) -> Result<IssuedNodeCert, PkiError> {
    let key_pair = KeyPair::generate()?;

    let mut params = CertificateParams::new(vec![node_id.to_string()])?;
    params.distinguished_name.push(DnType::CommonName, node_id);
    params.is_ca = IsCa::NoCa;
    let now = time::OffsetDateTime::now_utc();
    params.not_before = now;
    params.not_after = now + time::Duration::days(i64::from(ttl_days));

    let cert = params.signed_by(&key_pair, &ca.ca_cert, &ca.ca_key)?;
    let cert_der = cert.der().clone();
    let cert_pem = der_to_pem_cert(cert_der.as_ref());
    let key_pem = key_pair.serialize_pem();

    Ok(IssuedNodeCert {
        cert_der,
        cert_pem,
        key_pem,
    })
}

// ── provision_node_cert_if_absent ──────────────────────────────────────────

/// If `cert_path` and `key_path` do not both exist, generate a new node
/// certificate signed by the CA from environment variables and write them to
/// disk.
///
/// Returns `true` if a new cert was provisioned, `false` if both files were
/// already present (no action taken).
///
/// # Environment variables required
/// `TLS_CA_CERT_PATH` and `TLS_CA_KEY_PATH` must be set.
pub fn provision_node_cert_if_absent(
    node_id: &str,
    cert_path: &Path,
    key_path: &Path,
    ttl_days: u32,
) -> Result<bool, PkiError> {
    if cert_path.exists() && key_path.exists() {
        return Ok(false);
    }
    let ca = NodeCaConfig::from_env()?;
    let issued = sign_node_cert(node_id, &ca, ttl_days)?;
    issued.save(cert_path, key_path)?;
    Ok(true)
}

// ── PEM helpers ────────────────────────────────────────────────────────────

/// Encodes DER bytes as a PEM CERTIFICATE block (no external crate needed).
fn der_to_pem_cert(der: &[u8]) -> String {
    let b64 = base64_encode(der);
    let mut out = String::from("-----BEGIN CERTIFICATE-----\n");
    for chunk in b64.as_bytes().chunks(64) {
        // SAFETY: base64_encode only emits ASCII bytes from the table or '='.
        out.push_str(unsafe { std::str::from_utf8_unchecked(chunk) });
        out.push('\n');
    }
    out.push_str("-----END CERTIFICATE-----\n");
    out
}

fn base64_encode(data: &[u8]) -> String {
    const TABLE: &[u8; 64] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
    let mut out = Vec::with_capacity((data.len() + 2) / 3 * 4);
    for chunk in data.chunks(3) {
        let b0 = chunk[0] as usize;
        let b1 = if chunk.len() > 1 {
            chunk[1] as usize
        } else {
            0
        };
        let b2 = if chunk.len() > 2 {
            chunk[2] as usize
        } else {
            0
        };
        out.push(TABLE[(b0 >> 2) & 0x3F]);
        out.push(TABLE[((b0 << 4) | (b1 >> 4)) & 0x3F]);
        out.push(if chunk.len() > 1 {
            TABLE[((b1 << 2) | (b2 >> 6)) & 0x3F]
        } else {
            b'='
        });
        out.push(if chunk.len() > 2 {
            TABLE[b2 & 0x3F]
        } else {
            b'='
        });
    }
    // SAFETY: all bytes are ASCII from TABLE or '='.
    unsafe { String::from_utf8_unchecked(out) }
}

// ── Tests ──────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Write;
    use std::sync::Mutex;
    use tempfile::NamedTempFile;

    static ENV_LOCK: Mutex<()> = Mutex::new(());

    // ── helpers ────────────────────────────────────────────────────────────

    fn make_ca() -> (NodeCaConfig, String, String) {
        NodeCaConfig::generate().unwrap()
    }

    fn write_temp(content: &str) -> NamedTempFile {
        let mut f = NamedTempFile::new().unwrap();
        f.write_all(content.as_bytes()).unwrap();
        f.flush().unwrap();
        f
    }

    // ── base64 / PEM ───────────────────────────────────────────────────────

    #[test]
    fn base64_encode_empty() {
        assert_eq!(base64_encode(b""), "");
    }

    #[test]
    fn base64_encode_known_values() {
        assert_eq!(base64_encode(b"Man"), "TWFu");
        assert_eq!(base64_encode(b"Ma"), "TWE=");
        assert_eq!(base64_encode(b"M"), "TQ==");
    }

    #[test]
    fn der_to_pem_cert_has_correct_headers() {
        let pem = der_to_pem_cert(b"hello");
        assert!(pem.starts_with("-----BEGIN CERTIFICATE-----\n"));
        assert!(pem.ends_with("-----END CERTIFICATE-----\n"));
    }

    #[test]
    fn der_to_pem_cert_is_loadable_by_rustls_pemfile() {
        let (ca, _, _) = make_ca();
        let issued = sign_node_cert("node-test", &ca, 90).unwrap();
        let pem = issued.cert_pem.clone();

        let mut reader = std::io::BufReader::new(pem.as_bytes());
        let certs: Vec<_> = rustls_pemfile::certs(&mut reader)
            .collect::<Result<_, _>>()
            .unwrap();
        assert_eq!(certs.len(), 1);
        assert_eq!(certs[0].as_ref(), issued.cert_der.as_ref());
    }

    // ── NodeCaConfig::generate ─────────────────────────────────────────────

    #[test]
    fn generate_ca_produces_valid_pem() {
        let (_, cert_pem, key_pem) = make_ca();
        assert!(cert_pem.contains("BEGIN CERTIFICATE"));
        assert!(key_pem.contains("BEGIN"));
    }

    // ── NodeCaConfig::from_pem_files ───────────────────────────────────────

    #[test]
    fn from_pem_files_loads_generated_ca() {
        let (_, cert_pem, key_pem) = make_ca();
        let cert_file = write_temp(&cert_pem);
        let key_file = write_temp(&key_pem);
        let result = NodeCaConfig::from_pem_files(cert_file.path(), key_file.path());
        assert!(result.is_ok(), "{result:?}");
    }

    #[test]
    fn from_pem_files_fails_with_missing_cert() {
        let (_, _, key_pem) = make_ca();
        let key_file = write_temp(&key_pem);
        let result =
            NodeCaConfig::from_pem_files(Path::new("/nonexistent/ca.pem"), key_file.path());
        assert!(matches!(result, Err(PkiError::ReadFile(..))));
    }

    #[test]
    fn from_pem_files_fails_with_missing_key() {
        let (_, cert_pem, _) = make_ca();
        let cert_file = write_temp(&cert_pem);
        let result =
            NodeCaConfig::from_pem_files(cert_file.path(), Path::new("/nonexistent/ca.key"));
        assert!(matches!(result, Err(PkiError::ReadFile(..))));
    }

    // ── NodeCaConfig::from_env ─────────────────────────────────────────────

    #[test]
    fn from_env_fails_without_ca_cert_var() {
        let _g = ENV_LOCK.lock().unwrap_or_else(|e| e.into_inner());
        std::env::remove_var("TLS_CA_CERT_PATH");
        std::env::remove_var("TLS_CA_KEY_PATH");
        let result = NodeCaConfig::from_env();
        assert!(matches!(result, Err(PkiError::MissingCaCert)));
    }

    #[test]
    fn from_env_fails_without_ca_key_var() {
        let _g = ENV_LOCK.lock().unwrap_or_else(|e| e.into_inner());
        let (_, cert_pem, _) = make_ca();
        let cert_file = write_temp(&cert_pem);
        std::env::set_var("TLS_CA_CERT_PATH", cert_file.path());
        std::env::remove_var("TLS_CA_KEY_PATH");
        let result = NodeCaConfig::from_env();
        std::env::remove_var("TLS_CA_CERT_PATH");
        assert!(matches!(result, Err(PkiError::MissingCaKey)));
    }

    #[test]
    fn from_env_succeeds_with_valid_vars() {
        let _g = ENV_LOCK.lock().unwrap_or_else(|e| e.into_inner());
        let (_, cert_pem, key_pem) = make_ca();
        let cert_file = write_temp(&cert_pem);
        let key_file = write_temp(&key_pem);
        std::env::set_var("TLS_CA_CERT_PATH", cert_file.path());
        std::env::set_var("TLS_CA_KEY_PATH", key_file.path());
        let result = NodeCaConfig::from_env();
        std::env::remove_var("TLS_CA_CERT_PATH");
        std::env::remove_var("TLS_CA_KEY_PATH");
        assert!(result.is_ok(), "{result:?}");
    }

    // ── sign_node_cert ─────────────────────────────────────────────────────

    #[test]
    fn sign_node_cert_returns_non_empty_cert_and_key() {
        let (ca, _, _) = make_ca();
        let issued = sign_node_cert("node-1", &ca, 365).unwrap();
        assert!(!issued.cert_der.as_ref().is_empty());
        assert!(issued.cert_pem.contains("BEGIN CERTIFICATE"));
        assert!(issued.key_pem.contains("BEGIN"));
    }

    #[test]
    fn sign_node_cert_chains_to_ca() {
        // Verify that the issued cert's chain validates against the CA in WebPKI.
        let (ca, cert_pem, _) = make_ca();
        let ca_der = {
            let mut reader = std::io::BufReader::new(cert_pem.as_bytes());
            let der = rustls_pemfile::certs(&mut reader).next().unwrap().unwrap();
            der
        };

        let issued = sign_node_cert("node-chain-test", &ca, 365).unwrap();

        // Add CA cert to a root store — must succeed (CA cert is valid).
        let mut root_store = rustls::RootCertStore::empty();
        root_store.add(ca_der).unwrap();

        // Build a client verifier that trusts our CA: if the CA cert is
        // accepted, leaf certs signed by the same key will pass WebPKI chain
        // validation (signature + issuer DN match).
        use rustls::server::WebPkiClientVerifier;
        let verifier = WebPkiClientVerifier::builder(std::sync::Arc::new(root_store)).build();
        assert!(verifier.is_ok(), "CA cert accepted by WebPKI root store");
        // The leaf cert DER must be non-empty and parseable.
        assert!(!issued.cert_der.as_ref().is_empty());
    }

    #[test]
    fn sign_node_cert_with_zero_ttl_does_not_panic() {
        let (ca, _, _) = make_ca();
        let result = sign_node_cert("node-zero-ttl", &ca, 0);
        assert!(result.is_ok());
    }

    #[test]
    fn sign_node_cert_different_keys_per_call() {
        let (ca, _, _) = make_ca();
        let c1 = sign_node_cert("node-a", &ca, 30).unwrap();
        let c2 = sign_node_cert("node-b", &ca, 30).unwrap();
        assert_ne!(
            c1.key_pem, c2.key_pem,
            "each call must generate a fresh key pair"
        );
    }

    // ── IssuedNodeCert::save ───────────────────────────────────────────────

    #[test]
    fn save_writes_readable_pem_files() {
        let (ca, _, _) = make_ca();
        let issued = sign_node_cert("node-save", &ca, 365).unwrap();

        let cert_file = NamedTempFile::new().unwrap();
        let key_file = NamedTempFile::new().unwrap();
        issued.save(cert_file.path(), key_file.path()).unwrap();

        let cert_bytes = std::fs::read(cert_file.path()).unwrap();
        let mut reader = std::io::BufReader::new(cert_bytes.as_slice());
        let certs: Vec<_> = rustls_pemfile::certs(&mut reader)
            .collect::<Result<_, _>>()
            .unwrap();
        assert_eq!(certs.len(), 1);

        let key_bytes = std::fs::read(key_file.path()).unwrap();
        let mut kreader = std::io::BufReader::new(key_bytes.as_slice());
        let key = rustls_pemfile::private_key(&mut kreader).unwrap();
        assert!(key.is_some());
    }

    // ── provision_node_cert_if_absent ──────────────────────────────────────

    #[test]
    fn provision_skips_when_both_files_exist() {
        let cert_file = NamedTempFile::new().unwrap();
        let key_file = NamedTempFile::new().unwrap();
        let provisioned =
            provision_node_cert_if_absent("node", cert_file.path(), key_file.path(), 365).unwrap();
        assert!(!provisioned);
    }

    #[test]
    fn provision_creates_cert_and_key_when_both_absent() {
        let _g = ENV_LOCK.lock().unwrap_or_else(|e| e.into_inner());
        let (_, cert_pem, key_pem) = make_ca();
        let ca_cert_file = write_temp(&cert_pem);
        let ca_key_file = write_temp(&key_pem);
        std::env::set_var("TLS_CA_CERT_PATH", ca_cert_file.path());
        std::env::set_var("TLS_CA_KEY_PATH", ca_key_file.path());

        let dir = tempfile::tempdir().unwrap();
        let cert_path = dir.path().join("node.crt");
        let key_path = dir.path().join("node.key");

        let provisioned =
            provision_node_cert_if_absent("new-node", &cert_path, &key_path, 365).unwrap();

        std::env::remove_var("TLS_CA_CERT_PATH");
        std::env::remove_var("TLS_CA_KEY_PATH");

        assert!(provisioned);
        assert!(cert_path.exists());
        assert!(key_path.exists());

        let cert_data = std::fs::read(&cert_path).unwrap();
        let mut reader = std::io::BufReader::new(cert_data.as_slice());
        let certs: Vec<_> = rustls_pemfile::certs(&mut reader)
            .collect::<Result<_, _>>()
            .unwrap();
        assert_eq!(certs.len(), 1);
    }

    #[test]
    fn provision_creates_when_cert_exists_but_key_missing() {
        let _g = ENV_LOCK.lock().unwrap_or_else(|e| e.into_inner());
        let (_, cert_pem, key_pem) = make_ca();
        let ca_cert_file = write_temp(&cert_pem);
        let ca_key_file = write_temp(&key_pem);
        std::env::set_var("TLS_CA_CERT_PATH", ca_cert_file.path());
        std::env::set_var("TLS_CA_KEY_PATH", ca_key_file.path());

        // cert exists, key does not
        let cert_file = NamedTempFile::new().unwrap();
        let key_path = cert_file.path().with_extension("key.tmp");
        let _ = std::fs::remove_file(&key_path);

        let provisioned =
            provision_node_cert_if_absent("node", cert_file.path(), &key_path, 365).unwrap();

        std::env::remove_var("TLS_CA_CERT_PATH");
        std::env::remove_var("TLS_CA_KEY_PATH");
        assert!(provisioned);
        assert!(key_path.exists());
        let _ = std::fs::remove_file(&key_path);
    }

    #[test]
    fn provision_fails_without_env_vars() {
        let _g = ENV_LOCK.lock().unwrap_or_else(|e| e.into_inner());
        std::env::remove_var("TLS_CA_CERT_PATH");
        std::env::remove_var("TLS_CA_KEY_PATH");

        let dir = tempfile::tempdir().unwrap();
        let cert_path = dir.path().join("node.crt");
        let key_path = dir.path().join("node.key");

        let result = provision_node_cert_if_absent("node", &cert_path, &key_path, 365);
        assert!(matches!(result, Err(PkiError::MissingCaCert)));
    }
}
